name: website-tracker
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - requests>=2.31.0
  - beautifulsoup4>=4.12.0
  - pyyaml>=6.0.1
  - python-dotenv>=1.0.0
  - pip:
    - google-auth>=2.27.0
    - google-auth-oauthlib>=1.2.0
    - google-auth-httplib2>=0.2.0
    - google-api-python-client>=2.120.0
    - tenacity>=8.2.3
variables:
  PYTHONPATH: $CONDA_PREFIX/lib/python3.11/site-packages