name: Website Content Monitor

on:
  schedule:
    # - cron: '0 */6 * * *'  # Run every 6 hours
    # - cron: '0 0 * * *'     # Run daily at midnight
    - cron: '0 9 * * 2'     # Run weekly on Tuesday at 9:00 AM
    # - cron: '0 0 * * 0'     # Run weekly on Sunday
    # - cron: '0 0 1 * *'     # Run monthly on the 1st
  workflow_dispatch:  # Allow manual trigger
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'config/**'
      - '.github/workflows/**'

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2  # Fetch last 2 commits for change detection
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Cache website data
      uses: actions/cache@v4
      with:
        path: data
        key: website-data-${{ github.run_id }}
        restore-keys: |
          website-data-
    
    - name: Run website monitor
      env:
        GMAIL_CLIENT_ID: ${{ secrets.GMAIL_CLIENT_ID }}
        GMAIL_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET }}
        GMAIL_REFRESH_TOKEN: ${{ secrets.GMAIL_REFRESH_TOKEN }}
        GMAIL_FROM_EMAIL: ${{ secrets.GMAIL_FROM_EMAIL }}
      run: python -m src
    
    - name: Upload logs
      if: always()  # Upload logs even if monitoring fails
      uses: actions/upload-artifact@v4
      with:
        name: monitor-logs
        path: logs/
        retention-days: 7  # Keep logs for 7 days